server:
  port: 8090 
  servlet:
    context-path: /fleetwood

security: 
  oauth2: 
    client: 
      client-id: Fleetwood
      client-secret: y471l12D2y55U5558rd2

# authorization server
accessTokenUri: http://192.168.1.2:8080/authorization/oauth/token
userAuthorizationUri: http://192.168.1.2:8080/authorization/oauth/authorize



# resource server
#producerBaseURL: http://localhost:8081/sharewood/api/
#sharewoodPhotoBaseURL: http://localhost:8081/sharewood/api/photos
# edit to match your host IP address
producerBaseURL: http://192.168.1.2:5555/sharewood/api/
sharewoodPhotoBaseURL: http://192.168.1.2:5555/sharewood/api/photos
#producerBaseURL: http://localhost:8081/api/
#sharewoodPhotoBaseURL: http://localhost:8081/api/photos






# client
tempDir: /home/dominique/Images/client/tmp/

# Logging pattern for the console
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
 
